name: 'smart-copy-cat'
description: 'Copies only trigger-specified paths to another repository'
author: 'ItsGiantCookie'
branding:
  icon: copy
  color: purple

inputs:
  output-repo:
    required: true
    description: 'Target repository in format owner/repo'
  output-branch:
    required: true
    description: 'Target branch name'
  path-pattern-to-prune:
    description: 'Path segment to remove'
    default: ''
  path-pattern-to-insert:
    description: 'Path segment to insert'
    default: ''
  commit-message-prefix:
    default: '[Auto-Sync] '
  pr-title:
    default: 'Automated file sync'
  pr-message:
    default: 'Files copied via GitHub Actions'
  git-token:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Initialize environment
      shell: bash
      run: |
        echo "PR_BRANCH=copy-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV
        echo "TMP_SRCDIR=./source" >> $GITHUB_ENV
        echo "TMP_DSTDIR=./dest" >> $GITHUB_ENV

    - name: Checkout source repository
      uses: actions/checkout@v4
      with:
        path: ${{ env.TMP_SRCDIR }}
        fetch-depth: 0

    - name: Get workflow paths
      shell: bash
      run: |
        # Extract workflow filename from workflow_ref
        WORKFLOW_FILE=$(basename "${{ github.workflow_ref }}" '@*')
        
        # Get workflow content from local file since API access might fail
        WORKFLOW_PATH=".github/workflows/$WORKFLOW_FILE"
        
        if [ -f "$WORKFLOW_PATH" ]; then
          # Extract paths using yq (YAML processor)
          PATHS=$(yq e '.on.push.paths[]' "$WORKFLOW_PATH")
          echo "$PATHS" | while read -r path; do
            echo "$path" | sed 's/\*\*/*/g; s/^/"/; s/$/"/'
          done > trigger_paths.txt
        else
          echo "::warning::Using default paths from action inputs"
          echo "${{ github.event.inputs.paths || 'co79_GerRng_Zug_3_0.VR/**' }}" > trigger_paths.txt
        fi

    - name: Get matching files
      shell: bash
      run: |
        # Use find with exact path patterns
        find "${{ env.TMP_SRCDIR }}" -type f \( $(sed 's/^/-path /; s/$/ -o/' trigger_paths.txt) -false \) > matched_files.txt
        
        # Make paths relative to source directory
        sed "s|^${{ env.TMP_SRCDIR }}/||" matched_files.txt > changed_files.txt
        
        if [ ! -s changed_files.txt ]; then
          echo "::warning::No matching files found to copy"
          exit 0
        fi

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.output-repo }}
        token: ${{ inputs.git-token }}
        path: ${{ env.TMP_DSTDIR }}

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global url."https://${{ inputs.git-token }}@github.com/".insteadOf "https://github.com/"

    - name: Prepare target branch
      working-directory: ${{ env.TMP_DSTDIR }}
      shell: bash
      run: |
        git checkout -b ${{ env.PR_BRANCH }}

    - name: Copy and transform files
      shell: bash
      run: |
        while IFS= read -r src_file; do
          dest_file=$(echo "$src_file" | sed "s|^${{ inputs.path-pattern-to-prune }}|${{ inputs.path-pattern-to-insert }}|")
          mkdir -p "${{ env.TMP_DSTDIR }}/$(dirname "$dest_file")"
          cp -v "${{ env.TMP_SRCDIR }}/$src_file" "${{ env.TMP_DSTDIR }}/$dest_file"
        done < changed_files.txt

    - name: Commit changes
      working-directory: ${{ env.TMP_DSTDIR }}
      shell: bash
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add -A
          git commit -m "${{ inputs.commit-message-prefix }}Copied files from ${{ github.repository }}"
          git push origin ${{ env.PR_BRANCH }}
        else
          echo "::notice::No changes to commit"
          exit 0
        fi

    - name: Create pull request
      shell: bash
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ inputs.git-token }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ inputs.output-repo }}/pulls" \
          -d '{
            "title": "${{ inputs.pr-title }}",
            "head": "'${{ env.PR_BRANCH }}'",
            "base": "'${{ inputs.output-branch }}'",
            "body": "${{ inputs.pr-message }}\n\nSource: ${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}"
          }'
